env: JRUBY_OPTS=--debug
language: ruby
sudo: false
cache: bundler
services:
  - postgresql
rvm:
  - jruby-9.2.0.0
  - 2.5.1
  - 2.4.4
  - 2.3.3
  - 2.2.6
before_install:
  - gem update --system
  - gem install bundler
script: bundle exec rake build spec
